{% set name = "porespy" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 991c2151a401467028c3062abc59b12d369804e923a66d21e26a4af59fe8d4cf

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
  run:
    - dask
    - deprecated
    - edt
    - matplotlib-base
    - numba
    - numpy
    - openpnm
    - pandas
    - psutil
    - rich
    - python
    - scikit-image
    - scipy
    - setuptools
    - tqdm
    - pywavelets

test:
  imports:
    - porespy

about:
  home: https://github.com/PMEAL/porespy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of tools for characterizing and analying 3D images of porous materials
  description: PoreSpy is a collection of image analysis tool used to extract information from 3D images of porous materials (typically obtained from X-ray tomography). There are many packages that offer generalized image analysis tools (i.e Skimage and Scipy.NDimage in the Python environment, ImageJ, MatLab's Image Processing
    Toolbox), but the all require building up complex scripts or macros to accomplish tasks of specific use to porous media. The aim of PoreSpy is to provide a set of pre-written tools for all the common porous media measurements.

  doc_url: https://porespy.org/
  dev_url: https://github.com/PMEAL/porespy/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
